apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
    - image: localhost:5000/newslingo-frontend
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: newsling-frontend
        chartPath: helm
        namespace: newslingo
        createNamespace: true
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO}}"
          image.tag: "{{.IMAGE_TAG}}"
