"""Sync existing database

Revision ID: 42f3925aec52
Revises: 
Create Date: 2025-02-07 15:28:05.022293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42f3925aec52'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('o_auth_account_providerId_key', table_name='o_auth_account')
    op.drop_index('o_auth_account_userId_key', table_name='o_auth_account')
    op.drop_table('o_auth_account')
    op.drop_index('ix_news_english_id', table_name='news_english')
    op.drop_index('ix_news_english_news_id', table_name='news_english')
    op.drop_table('news_english')
    op.drop_table('board_comment')
    op.drop_index('board_name_key', table_name='board')
    op.drop_table('board')
    op.drop_table('post')
    op.drop_index('ix_news_id', table_name='news')
    op.drop_index('ix_news_news_id', table_name='news')
    op.drop_table('news')
    op.drop_index('ix_news_korean_id', table_name='news_korean')
    op.drop_index('ix_news_korean_news_id', table_name='news_korean')
    op.drop_table('news_korean')
    op.drop_index('ix_comment_id', table_name='comment')
    op.drop_index('ix_comment_news_id', table_name='comment')
    op.drop_index('ix_comment_user_id', table_name='comment')
    op.drop_table('comment')
    op.drop_index('user_email_key', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('providerId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('profilePicture', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('user_email_key', 'user', ['email'], unique=True)
    op.create_table('comment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('parentId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.news_id'], name='comment_news_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parentId'], ['comment.id'], name='comment_parentId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name='comment_userId_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='comment_pkey')
    )
    op.create_index('ix_comment_user_id', 'comment', ['userId'], unique=False)
    op.create_index('ix_comment_news_id', 'comment', ['news_id'], unique=False)
    op.create_index('ix_comment_id', 'comment', ['id'], unique=False)
    op.create_table('news_korean',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.news_id'], name='news_korean_news_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='news_korean_pkey')
    )
    op.create_index('ix_news_korean_news_id', 'news_korean', ['news_id'], unique=False)
    op.create_index('ix_news_korean_id', 'news_korean', ['id'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('news_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('news_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('thum_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('broadcast_date', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='news_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_news_news_id', 'news', ['news_id'], unique=True)
    op.create_index('ix_news_id', 'news', ['id'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('post_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('boardId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['boardId'], ['board.id'], name='post_boardId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name='post_userId_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='post_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('board',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('board_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='board_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('board_name_key', 'board', ['name'], unique=True)
    op.create_table('board_comment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('postId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parentId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parentId'], ['board_comment.id'], name='board_comment_parentId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['postId'], ['post.id'], name='board_comment_postId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name='board_comment_userId_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='board_comment_pkey')
    )
    op.create_table('news_english',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.news_id'], name='news_english_news_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='news_english_pkey')
    )
    op.create_index('ix_news_english_news_id', 'news_english', ['news_id'], unique=False)
    op.create_index('ix_news_english_id', 'news_english', ['id'], unique=False)
    op.create_table('o_auth_account',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('providerId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('accessToken', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refreshToken', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expiresAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('scope', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tokenType', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name='o_auth_account_userId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='o_auth_account_pkey')
    )
    op.create_index('o_auth_account_userId_key', 'o_auth_account', ['userId'], unique=True)
    op.create_index('o_auth_account_providerId_key', 'o_auth_account', ['providerId'], unique=True)
    # ### end Alembic commands ###
